### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by t7yang** [AdrianVovk/tree-view-autoresize#1]
1.12.0
UI: one dark ui

![2016-11-10_21-40-21](https://cloud.githubusercontent.com/assets/4502661/20179032/088e4082-a78f-11e6-9bb4-e405a908bcfd.gif)

**Comment by AdrianVovk** [comment]
Try turning off hover. That is still unfinished functionality.

**Comment by AdrianVovk** [comment]
This is fixed now
